export enum eMutationTypes {
  SET_USER = "SET_USER",
  CLEAR_USER = "CLEAR_USER",
  NAVIGATE_TO = "NAVIGATE_TO",
  INVALIDATE_NAVIGATE = "INVALIDATE_NAVIGATE",
  SET_PAYMENT = "SET_PAYMENT",
  CLEAR_PAYMENT = "CLEAR_PAYMENT",
  SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE",
}
